version: "3.9"

services:
  db:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    ports:
      - "${BILLING_DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${BILLING_DB_USER}
        POSTGRES_PASSWORD: ${BILLING_DB_PASSWORD}
        POSTGRES_DB: ${BILLING_DB_NAME}
        POSTGRES_HOST: ${BILLING_DB_HOST}
  server:
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - "${BILLING_APP_PORT}:${BILLING_APP_PORT}"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

